### ISSUE TITLE
Native fill ?

### ISSUE THREAD

**Issue by abhijithch** [FluxML/CuArrays.jl#14]
Is there a way I can create a `CuArray` of a constant?

**Comment by MikeInnes** [comment]
You can do

```julia
xs = CuArray(5,6)
xs .= 1
```

or equivalently use the `fill!` function, but I'll set up a more direct way to do this.

**Comment by MikeInnes** [comment]
Ok, you can now do `fill(CuArray, 0, (5,5))`, for example.

**Comment by abhijithch** [comment]
Cool, thanks.
