### ISSUE TITLE
confusing `sin` guidance in README

### ISSUE THREAD

**Issue by ssfrr** [FluxML/CuArrays.jl#17]
The readme uses the example `zs .= sin.(xs) .+ ys .* 2` to demo broadcasting, but then also says

> When broadcasting, watch out for errors like:
> ```
> julia> sin.(cos.(xs))
> ERROR: CUDA error: invalid program counter (code #718, ERROR_INVALID_PC)
> A current limitation of CUDAnative means that you'll need to restart Julia and use CuArrays.sin, > CuArrays.cos etc in this case.
> ```

It's not clear to me why the usage of `sin` is OK in the first but not in the second. It might help to expand on what exactly to watch out for in the 2nd case.

**Comment by MikeInnes** [comment]
For the first example you'd have to `import CuArrays: sin` first. That's confusing so I've edited it out. Let me know if it's still unclear.
