### ISSUE TITLE
Reduce with unary operators

### ISSUE THREAD

**Issue by maleadt** [FluxML/CuArrays.jl#4]
In trying to get ForwardDiff's main example to work, I'm trying to reduce with binary operators:

```julia
xs = rand(5)
sum(sin, xs)
```

Initially, it looked like CuArrays supports this:
```julia
xs = CuArray(rand(5))
sum(sin, xs)
```

But as it turns out, this does a CPU reduction because of (what I presume to be) a missing definition:
```julia
Base.sum(f::Base.Callable, xs::CuArray) = reduce(f, 0, xs)
```

But now it shows how `CuArrays.reduce_grid` calls `op` in a binary fashion, which obviously fails:
```julia
CUDAnative.code_warntype(CuArrays.reduce_grid,
                         (typeof(CUDAnative.sin), Float64,
                          CUDAnative.CuDeviceArray{Float64,1,CUDAnative.AS.Global},
                          CUDAnative.CuDeviceArray{Float64,1,CUDAnative.AS.Global},
                          Int32))

val::Any = (op::CUDAnative.#sin)(val::Any, (Base.pointerref)((Core.getfield)((Core.getfield)(input::CUDAnative.CuDeviceArray{Float64,1,CUDAnative.AS.Global}, :ptr)::CUDAnative.DevicePtr{Float64,CUDAnative.AS.Global}, :ptr)::Ptr{Float64}, (Base.zext_int)(Int64, i::UInt32)::Int64, 8)::Float64)::Any
```

```julia
Base.sum(f::Base.Callable, xs::CuArray) = reduce(f, 0, xs)

xs = CuArray(rand(5))
sum(sin, xs)

ERROR: LoadError: error compiling reduce_grid: emit_allocobj for CuArrays/src/reduction.jl:58 requires the dynamic_alloc language feature, which is disabled

```

**Comment by maleadt** [comment]
ah never mind, I bugged out on those extra defs. I guess the following should work:

```julia
Base.sum(f::Base.Callable, xs::CuArray) = reduce(+, 0, f.(xs))
Base.prod(f::Base.Callable, xs::CuArray) = reduce(*, 1, f.(xs))
```

Not sure how optimal this is, but probably should be part of CuArrays in some form. I'll leave this open for you to see this, but the rest of this issue is invalid.

**Comment by MikeInnes** [comment]
Julia builds all of this on top of `mapreduce`. Currently I only have `mapreduce(identity, op, xs)` implemented; it should in principle be easy to add a mapping function to your reduction kernel, though when I tried it I had correctness issues.

You might know the right way to fix that, but failing that I can just define `mapreduce(f, op, v0, xs)` = `reduce(op, v0, f.(xs)` as a kludge.
